config/routes.rb
Rails.application.routes.draw do

  root 'kittens#index'

  resources :kittens

end

app/models/kitten.rb
class Kitten < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController

  def index
    @kittens = Kitten.all
    respond_to do |format|
      format.html
      format.json { render :json => @kittens }
      format.xml { render :xml => @kittens }
    end
  end

  def show
    @kitten = Kitten.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render :json => @kitten }
      format.xml { render :xml => @kitten }
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])
    if @kitten.update_attributes(kitten_params)
      flash[:success] = "Kitten updated!"
      redirect_to root_url
    else
      
      render 'edit'
    end
  end

  def destroy
    Kitten.find(params[:id]).destroy
    flash[:success] = "Kitten deleted"
    redirect_to root_url
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      flash[:success] = "Kitten created!"
      redirect_to root_url
    else
      
      render 'new'
    end
  end

  private

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_fields.html.erb
<%= f.label :name %>
<%= f.text_field :name %></br>

<%= f.label :age %>
<%= f.text_field :age %></br>

<%= f.label :cuteness %>
<%= f.text_field :cuteness %></br>

<%= f.label :softness %>
<%= f.text_field :softness %></br>

app/views/kittens/_kitten.html.erb
<li>

  <%= link_to kitten.name, kitten %>
  <%= link_to "Edit kitten", edit_kitten_path(kitten) %>
    | <%= link_to "delete", kitten, method: :delete, data: { confirm: "You sure?" } %>

</li>

app/views/kittens/edit.html.erb
<h1>Update kitten</h1>

    <%= form_for(@kitten) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "Save changes" %>
    <% end %>
</br><%= link_to "Delete this kitten", kitten_path, method: :delete, data: { confirm: "You sure?" } %>
</br><%= link_to "Home", kittens_path %>

app/views/kittens/index.html.erb
<h1>All kittens</h1>

<h2><%= render 'shared/messages' %></h2>

<ul>

  <%= render @kittens %> <!-- rails automatically looks for a partial called _kitten.html.erb -->
</ul>
<%= link_to "New kitten", new_kitten_path %>

app/views/kittens/new.html.erb
<h1>Create new kitten</h1>


    <%= form_for(@kitten) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "Create kitten" %>
    <% end %>

</br><%= link_to "Home", kittens_path %>

app/views/kittens/show.html.erb
      <h1>Show kitten</h1>
        <p>Name: <%= @kitten.name %></p>
        <p>Age: <%= @kitten.age %></p>
        <p>Cuteness: <%= @kitten.cuteness %></p>
        <p>Softness: <%= @kitten.softness %></p>
</br><%= link_to "Delete this kitten", kitten_path, method: :delete, data: { confirm: "You sure?" } %>
</br><%= link_to "Home", kittens_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OdinKittens</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_messages.html.erb
<div class="container">
  <div>
    <% flash.each do |name, message| %>
      <div class="alert alert-info" role="alert">
        <ul style="list-style-type: none;">
          <li>
            <%= content_tag :div, message, :id => "flash_#{name}"%>
          </li>
        </ul>
      </div>
    <% end %>
  </div>
</div>